<a href="https://colab.research.google.com/github/MxD-lab/SNN_Simulation/blob/HW/HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [92]:
# -*- coding: utf-8 -*-
import os
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import math
import numpy 



In [93]:
"""
input_num :インプット層のニューロン数
hidden_num ：隠れ層のニューロン数
output_num ：出力層のニューロン数
"""
N = 4#データ数(ミニバッチ)
input_num = 2 
hidden_num = 12
output_num = 1

In [94]:
sample_count = 200
s = np.zeros((input_num,hidden_num))
diff = np.zeros((input_num,hidden_num))

In [95]:
"""
重み、バイアス、初期設定
W1：隠れ層の重み
B1:隠れ層のバイアス
W2:出力層の重み
B2:隠れ層のバイアス
"""


W1 = np.random.rand(input_num,hidden_num)
B1 = np.random.rand(hidden_num)
W2 = np.random.rand(hidden_num,output_num)
B2 = np.random.rand(output_num)

In [96]:
#シグモイド関数（出力層）

def sigmoid(x):
  return 1/(1+np.exp(-x))
"""
def sigmoid(x):
  if x < -5:
    return 0

  if -5<=x<=5:
    return 1/10*x+0.5

  if 5 < x:
    return 1
""" 
"""
#ReLU関数（隠れ層）
def relu(x):
  return np.maximum(0,x)
"""
"""
ReLU関数
x:入力,
n:x切片,
a:傾き
"""
def relu(x,n,a,min,max):
  
  if x<min:
    out = min
  
  if min<=x<=max:
    y = a*(x-n)
    out = np.maximum(y,0)

  if x>max:
    out = max
  
  return out


In [97]:
"""
a = np.zeros(1)
for i in range(sample_count):
  if i%20 == 0:
    a[i] = np.insert(a,i,1)
  else:
    a[i] = np.insert(a,i,0)



"""


'\na = np.zeros(1)\nfor i in range(sample_count):\n  if i%20 == 0:\n    a[i] = np.insert(a,i,1)\n  else:\n    a[i] = np.insert(a,i,0)\n\n\n\n'

In [98]:
"""
def PG(sample_count,pulse_msec):
  a = np.zeros(sample_count)
  count = 0
  for i in range(sample_count):
    if i%(1/pulse_msec/10) == 0:#dt = 10microsec
      a[i] = 1
      print("a")
    else:
      a[i] = 0
    count = count +1
    print(count)
 """     

'\ndef PG(sample_count,pulse_msec):\n  a = np.zeros(sample_count)\n  count = 0\n  for i in range(sample_count):\n    if i%(1/pulse_msec/10) == 0:#dt = 10microsec\n      a[i] = 1\n      print("a")\n    else:\n      a[i] = 0\n    count = count +1\n    print(count)\n '

In [99]:
#a = PG(sample_count,50)

In [100]:
x1 = np.zeros(sample_count)
  
for i in range(sample_count):
  if i%2 == 0:#dt = 10microsec
    x1[i] = 1
      
  else:
    x1[i] = 0

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

In [102]:
x2 = np.zeros(sample_count)
  
for i in range(sample_count):
  if i%2 == 0:#dt = 10microsec
    x2[i] = 1
      
  else:
    x2[i] = 0

In [110]:
for i in range(sample_count):
  if x1[i] == 1:
    for j in range(hidden_num):
      s[0][j] = s[0][j]+W1[0][j]

  if x2[i] == 1:
    for j in range(hidden_num):
      s[1][j] = s[1][j]+W1[1][j]
  

In [111]:
s

array([[ 24.53999623, 157.18236882,  79.7374099 ,  19.01585487,
         32.44158706,  66.10225364,   6.39882367,  49.35243315,
         37.98125053,  35.11041223, 186.49594708, 140.38960315],
       [118.25127617, 185.4305695 , 158.40321388, 171.59933824,
         41.32609114, 144.28653515, 167.40980303,  13.2537573 ,
         93.12659851,  47.66309305,  60.42496769, 142.51803081]])

In [112]:
for i in range(input_num):
  for j in range(hidden_num):
    diff[i][j] =relu(s[i][j],5,1,5,50) 

In [113]:
diff

array([[19.53999623, 50.        , 50.        , 14.01585487, 27.44158706,
        50.        ,  1.39882367, 44.35243315, 32.98125053, 30.11041223,
        50.        , 50.        ],
       [50.        , 50.        , 50.        , 50.        , 36.32609114,
        50.        , 50.        ,  8.2537573 , 50.        , 42.66309305,
        50.        , 50.        ]])